# Ξ·dag — the engine's import DAG (AST-derived by tools/imports.py, the single source of the
# build DAG).  {module: [imported module STEMS = their //paperkit target names]}.  Each
# pk_pyc's deps are its imports, so a consumer stages a module's transitive .pyc closure,
# not the flat engine.  REGENERATE (never hand-edit): tools/imports.py over ENGINE_SRCS.
IMPORTS = {
    "cache.py": ["layout"],
    "coherence.py": ["bib"],
    "discriminate.py": ["bib", "cache", "config", "driver", "gate", "grade", "grader"],
    "footdeps.py": ["bib", "resolver"],
    "gate.py": ["bib", "config", "project", "resolver"],
    "grader.py": ["config", "grade", "layout", "mutate", "resolver"],
    "layout.py": ["config"],
    "project.py": ["bib", "config", "rhetoric"],
    "resolver.py": ["config"],
    "rhetoric.py": ["bib"],
    "tests/_fixture_delta.py": ["_fixture_model", "_fixture_project", "discriminate"],
    "tests/_fixture_gate.py": ["_fixture_model", "_fixture_project", "gate"],
    "tests/_fixture_project.py": ["_fixture_model", "project"],
    "tests/boundaries_agree.py": ["resolver"],
    "tests/boundaries_coherence.py": ["coherence"],
    "tests/boundaries_config.py": ["config"],
    "tests/boundaries_corroboration.py": ["_fixture_delta", "_fixture_model"],
    "tests/boundaries_degrade.py": ["cache", "resolver"],
    "tests/boundaries_discriminate.py": ["_fixture_delta", "_fixture_model", "_fixture_project"],
    "tests/boundaries_dispatch.py": ["grader", "resolver"],
    "tests/boundaries_driver.py": ["driver"],
    "tests/boundaries_emit.py": ["_fixture_gate", "_fixture_model", "_fixture_project"],
    "tests/boundaries_env.py": ["resolver"],
    "tests/boundaries_footprint.py": ["_fixture_delta", "_fixture_model", "resolver"],
    "tests/boundaries_gate_json.py": ["_fixture_gate", "_fixture_model", "_fixture_project"],
    "tests/boundaries_grounding.py": ["_fixture_delta", "_fixture_gate", "_fixture_model"],
    "tests/boundaries_jobs.py": ["_fixture_gate", "_fixture_model"],
    "tests/boundaries_ladder.py": ["grade"],
    "tests/boundaries_memoize.py": ["_fixture_model", "discriminate"],
    "tests/boundaries_path.py": ["config", "resolver"],
    "tests/boundaries_references.py": ["project"],
    "tests/boundaries_sandbox.py": ["layout"],
    "tests/boundaries_surface.py": ["grade", "grader", "layout"],
    "tests/boundaries_target.py": ["project"],
    "tests/boundaries_without_k.py": ["_fixture_gate", "_fixture_model"],
}
