"""Ζ·starlark — the bib IS the build graph (no projected, checked-in BUILD).

A repository rule reads a paperkit project's warrants.bib during the FETCH phase — the one place
Starlark may read a file — and projects each CHECKED claim (@misc entry with a `check` field) into
the ONE recursive check target: an sh_test whose command resolves that claim's check (the leaf),
aggregated by a `gate` test_suite (the node), with an optional Δ `adequacy` target.  This
SUPERSEDES the checked-in BUILD projector: Bazel reads the bib DIRECTLY, so a target cannot drift
from its claim — Bazel re-fetches whenever warrants.bib changes.

Each target's `data` is its own project's files + the engine, plus the claim's DECLARED `reads`
(Ζ·foot, declare+audit): a bib field naming the cross-package projects the check touches
(`.` = root files like .githooks, or a sibling project).  Declaration is the cheap, portable
SOURCE; the repo-scoped Φ·footprint AUDITS it on demand (footdeps --audit: footprint ⊆ declared),
so the build graph needs no strace and a check cannot silently under-declare.  The node and the Δ
adequacy target use the UNION of the project's declared reads (the sweep reruns every check).

Starlark has no regex, so the parse is string ops on the regular `@type{key, field = {val}, ...}`
shape: an entry begins only at a LINE-START `@type{key,`; a claim is checkable iff a later field
line's name is `check`; a `result:<sibling>` check is an EDGE (wired by Ζ·hook in //:hook).
"""

def _entries(content):
    out = []
    key = None
    has_check = False
    sib = ""        # for a result:<sibling> check — the sibling it definitionally reads
    reads = []
    for raw in content.splitlines():
        s = raw.strip()
        if s.startswith("@") and "{" in s:
            if key != None:
                out.append((key, has_check, sib, reads))
            key = s.split("{", 1)[1].split(",", 1)[0].strip()
            has_check = False
            sib = ""
            reads = []
        elif key != None and "=" in s:
            name = s.split("=", 1)[0].strip()
            if name == "check":
                has_check = True
                val = s.split("{", 1)[1].rsplit("}", 1)[0].strip()
                if val.startswith("result:"):
                    sib = val.split(":", 1)[1].strip()
            elif name == "reads":
                inner = s.split("{", 1)[1].rsplit("}", 1)[0]
                reads = [t.strip() for t in inner.split(",") if t.strip()]
    if key != None:
        out.append((key, has_check, sib, reads))
    return out

def _data(tokens, files):
    """own files + engine (always) + each DECLARED read token → its project's filegroup
    (`.` → the root project's files; a sibling name → that project's files)."""
    out = {files: True, "@@//paperkit:engine": True}
    for t in tokens:
        if t == "paperkit":
            continue
        out["@@//:files" if t == "." else "@@//%s:files" % t] = True
    return sorted(out.keys())

def _sh_test(name, args, data):
    return "\n".join([
        'sh_test(',
        '    name = "%s",' % name,
        '    srcs = ["@@//tools:run.sh"],',
        '    args = [%s],' % ", ".join(['"%s"' % a for a in args]),
        '    data = [%s],' % ", ".join(['"%s"' % d for d in data]),
        '    size = "large",',
        '    visibility = ["//visibility:public"],',
        ')',
    ])

def _bib_repo_impl(repository_ctx):
    content = repository_ctx.read(repository_ctx.path(repository_ctx.attr.bib))
    proj = repository_ctx.attr.project
    files = "@@//:files" if proj == "." else "@@//%s:files" % proj
    parsed = _entries(content)
    checked = [(k, reads) for k, c, sib, reads in parsed if c and not sib]   # LEAVES (non-result)
    edges = [k for k, c, sib, reads in parsed if c and sib]                  # result: EDGES → //:hook
    out = ["# Generated by Ζ·starlark from %s — recursive check; data = own + engine + declared reads.\n" %
           str(repository_ctx.attr.bib)]
    if edges:
        out.append("# result: edges (claim → sibling gate), wired in //:hook by Ζ·hook: %s\n" % ", ".join(edges))
    # adequacy grades every checked claim; result: claims grade "imported" by DELEGATION
    # (Ξ·result-imported) without running the sibling, so they pull in NO deps — the union is just
    # the declared reads across the leaves.
    union = {}
    for k, reads in checked:
        for t in reads:
            union[t] = True
    for k, reads in checked:
        out.append(_sh_test(k, ["check", proj, k], _data(reads, files)))
    out.append(_sh_test("invariants", ["invariants", proj], [files, "@@//paperkit:engine"]))   # NODE
    tests = ['":%s"' % k for k, _ in checked] + ['":invariants"']
    out.append('test_suite(name = "gate", tests = [%s], visibility = ["//visibility:public"])' % ", ".join(tests))
    if repository_ctx.attr.adequacy:                              # Δ sweep reruns every check → UNION of reads
        out.append(_sh_test("adequacy", ["adequacy", proj], _data(union.keys(), files)))
    repository_ctx.file("BUILD.bazel", "\n".join(out) + "\n")

bib_repo = repository_rule(
    implementation = _bib_repo_impl,
    attrs = {
        "bib": attr.label(mandatory = True, allow_single_file = True),
        "project": attr.string(mandatory = True),
        "adequacy": attr.bool(default = False),
    },
)

def _bib_ext_impl(module_ctx):
    for mod in module_ctx.modules:
        for tag in mod.tags.project:
            bib_repo(name = tag.name, bib = tag.bib, project = tag.project, adequacy = tag.adequacy)

bib = module_extension(
    implementation = _bib_ext_impl,
    tag_classes = {
        "project": tag_class(attrs = {
            "name": attr.string(mandatory = True),
            "bib": attr.label(mandatory = True),
            "project": attr.string(mandatory = True),
            "adequacy": attr.bool(default = False),
        }),
    },
)
