r"""Ξ·dag·dotted — OWN paperkit/dag.bzl: render it, write it, and check it fresh.

This is `tools/imports.py`'s CLI half, rewritten clean.  Derivation lives in `tools.dagderive`;
this module owns the ARTIFACT — the header, the rendering, and the --write/--check contract that
`boundaries_dag_regen` invokes.

⚑ WHY IT IS A NEW FILE RATHER THAN AN EDIT.  `imports.py` carries 70 lint findings and the
per-file gate has no partial-credit path: an edit leaving it dirty is refused too, so staging
does not converge.  The gate's own advice is to extract the concern into a module written clean
in one pass and let the consumer import that.  Two extractions, one arc: `dagderive` (how edges
are derived) and this (what the artifact is).

⚑⚑ AND EVERY IMPORT HERE IS NAMED IN FULL (Ζ·path·retire).  Two cuts of this file were refused
for the same defect one level apart: a bare `import dagderive`, then a bare `import durable`
behind a `sys.path.insert`.  Both are unresolvable to mypy, which is the finding this arc keeps
producing — an undeclared import edge is invisible to the checker until someone names it, and the
injection is what HIDES that rather than what causes it.  `tools` is a package (Ζ·tools·package)
and `paperkit` is declared in pyproject, so both full names cost nothing.

⚑ THE HEADER IS EMITTED FROM HERE, AND IT CITES RATHER THAN RESTATES.  `render` used to split the
existing file on "IMPORTS = {" and copy whatever preceded it, so hand-maintained prose lived
INSIDE a regenerated artifact — carried verbatim through every regeneration, authored by nobody
the generator knew about, compared to nothing.  Every assertion in it happened to still be true:
accurate by luck, one design change from being a retired premise stamped into a fresh artifact.

A peer hit exactly that the same week — their ledger's header described a suballocation design
that had been REPLACED, rewritten into every new ledger, contradicting a block eighty lines above
it in the same file.  A derived artifact carrying a retired premise is worse than stale prose
because it LOOKS LIKE DATA.  The rule (project-dont-author): CITE THE AUTHORITY, NEVER RESTATE IT.

    python3 tools/dagbzl.py --check     # byte-compare against a fresh render (gated)
    python3 tools/dagbzl.py --write     # regenerate
"""
from __future__ import annotations

import ast
import sys
from pathlib import Path

from paperkit import durable
from tools import dagderive

HEADER = """# GENERATED by tools/dagbzl.py — do not edit, and do not add prose here: this whole file
# is rewritten, header included, so anything written by hand is lost or (worse) preserved past
# the point it stays true.  What this file IS, and why, is documented at the owner:
#   tools/dagderive.py        how the edges are derived (AST, never grep)
#   tools/dagbzl.py           how this artifact is rendered and gated
#   paperkit/components.bzl   the module partition the edges are derived over
# REGENERATE: python3 tools/dagbzl.py --write   ·   VERIFY: --check (byte-compare, gated)
"""


def literal(path: Path, name: str) -> dict[str, list[str]]:
    """Read the one dict literal `name` is bound to in a .bzl file.

    ⚑ The `literal_eval` Any is narrowed HERE, at the seam, so callers see a concrete type.
    """
    src = path.read_text()
    i = src.index(name + " = ")
    val: object = ast.literal_eval(src[src.index("{", i):src.index("\n}", i) + 2])
    if not isinstance(val, dict):
        return {}
    out: dict[str, list[str]] = {}
    for k, v in val.items():
        if isinstance(v, list):
            out[str(k)] = [str(x) for x in v]
    return out


def engine_srcs(eng: Path) -> list[str]:
    """Collect the module set the BUILD consumes, from the component partition.

    ⚑ DERIVED FROM `COMPONENTS`, NEVER A GLOB.  `paperkit/BUILD.bazel` builds ENGINE_SRCS this
    exact way ("EXPLICIT srcs (no globs), DERIVED from the component partition so the union is
    total by construction"), so reading the same literal keeps the generator's input equal to the
    build's BY CONSTRUCTION rather than by a second enumeration that agrees today.
    `boundaries_components.py` separately checks that partition against the real tree — which is
    where a NEW file nobody placed gets caught, a job this function must not also try to do.
    """
    return sorted(f for fs in literal(eng / "components.bzl", "COMPONENTS").values() for f in fs)


def render(rows: list[tuple[str, str]]) -> str:
    """Render dag.bzl in full — header INCLUDED, so nothing hand-written survives regeneration.

    ⚑ VALUES ARE MODULE PATHS, NOT BARE STEMS (Ξ·dag·dotted).  Both sides of an edge now name the
    namespace a Bazel target uses (`tests/boundaries_jobs.py` maps to
    `//paperkit:tests/boundaries_jobs`), so BUILD.bazel resolves a dep by stripping `.py` and
    needs no stem-to-target translation.
    """
    by_mod: dict[str, set[str]] = {}
    for m, i in rows:
        by_mod.setdefault(m, set()).add(i)
    body = "".join('    "{}": [{}],\n'.format(m, ", ".join(f'"{x}"' for x in sorted(v)))
                   for m, v in sorted(by_mod.items()))
    return HEADER + "IMPORTS = {\n" + body + "}\n"


def main(argv: list[str]) -> int:
    """Write or check paperkit/dag.bzl against a fresh derivation."""
    eng = Path(__file__).resolve().parents[1] / "paperkit"
    dag = eng / "dag.bzl"
    want = render(dagderive.edges(eng, engine_srcs(eng)))
    mode = argv[0] if argv else "--check"

    if mode == "--check":
        if dag.read_text() != want:
            sys.stderr.write("dagbzl.py --check: paperkit/dag.bzl is STALE — regenerate with "
                             "`python3 tools/dagbzl.py --write`\n")
            return 1
        sys.stdout.write("dagbzl.py --check: dag.bzl is fresh\n")
        return 0

    if mode == "--write":
        if dag.read_text() == want:
            sys.stdout.write("dagbzl.py --write: dag.bzl already fresh\n")
            return 0
        # Ζ·write·atomic — the generator eats its own cooking: a torn write of dag.bzl would
        # leave the build graph half-stated.
        durable.write_atomic(dag, want)
        sys.stdout.write("dagbzl.py --write: regenerated paperkit/dag.bzl\n")
        return 0

    sys.stderr.write(f"dagbzl.py: unknown mode {mode!r} — expected --check or --write\n")
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
