#!/usr/bin/env python3
"""Ξ·dag — enumerate a .py module's ENGINE-INTERNAL imports (the import edges), the analog of
def_sites.py for the mutation surface.  Emits `module<TAB>imported` per edge, where `imported` is
another module in the given set (a bare `import x` / `from x import …`, since the engine is on
sys.path).  Derived from the AST, never a grep (a grep matches the name in comments/strings — the
project↔rhetoric "cycle" was such a phantom).

The build DAG is a PROJECTION of this: each module's .pyc is a target whose deps are its imports, so
a consumer stages a module's transitive closure, not the flat engine — the incrementality is exact
by construction (Ξ·dag·build).  Usage: imports.py <module.py>… → the edges over that module set."""
import ast
import sys
from pathlib import Path


def imports(text, names):
    out = set()
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return out
    for n in ast.walk(tree):
        if isinstance(n, ast.Import):
            out |= {a.name for a in n.names if a.name in names}
        elif isinstance(n, ast.ImportFrom) and n.module in names:
            out.add(n.module)
    return out


def _literal(path, name):
    """The one value `name` is bound to in a .bzl file, read as a python literal."""
    src = path.read_text()
    i = src.index(name + " = ")
    return ast.literal_eval(src[src.index("{", i):src.index("\n}", i) + 2])


def engine_srcs(eng):
    """The module set the BUILD consumes — derived from the component partition, never a glob.

    paperkit/BUILD.bazel builds ENGINE_SRCS this exact way ("EXPLICIT srcs (no globs), DERIVED from
    the component partition so the union is total by construction"), and dag.bzl's header names the
    same set.  Reading COMPONENTS here keeps the generator's input equal to the build's by
    construction rather than by a second enumeration that agrees today.  boundaries_components.py
    separately checks that partition against the real tree, which is where a NEW file that nobody
    placed gets caught — a job this function must not also try to do."""
    return sorted(f for fs in _literal(eng / "components.bzl", "COMPONENTS").values() for f in fs)


def edges(eng, paths):
    names = {Path(p).stem for p in paths}
    out = []
    for p in paths:
        stem = Path(p).stem
        for imp in sorted(imports((eng / p).read_text(), names) - {stem}):
            out.append((p, imp))
    return out


def render(eng, rows):
    """dag.bzl's body — the header is PRESERVED, only the IMPORTS literal is rewritten."""
    by_mod = {}
    for m, i in rows:
        by_mod.setdefault(m, set()).add(i)
    body = "".join('    "%s": [%s],\n' % (m, ", ".join('"%s"' % x for x in sorted(v)))
                   for m, v in sorted(by_mod.items()))
    head = (eng / "dag.bzl").read_text().split("IMPORTS = {")[0]
    return head + "IMPORTS = {\n" + body + "}\n"


if __name__ == "__main__":
    argv = sys.argv[1:]
    # Ζ·dag·regen — the generator OWNS dag.bzl, so it can also WRITE it.  It emitted edges and
    # nothing invoked it, so every import edge added anywhere in the engine red the freshness check
    # until a human regenerated by hand — a generator built and left unwired (project-dont-author).
    # --check is the same computation asserting instead of writing: the gate runs THIS code path,
    # not a second reimplementation of it, so the check cannot drift from the writer.
    if argv and argv[0] in ("--write", "--check"):
        eng = Path(__file__).resolve().parents[1] / "paperkit"
        want = render(eng, edges(eng, engine_srcs(eng)))
        dag = eng / "dag.bzl"
        if argv[0] == "--check":
            if dag.read_text() != want:
                print("imports.py --check: paperkit/dag.bzl is STALE — regenerate with "
                      "`python3 tools/imports.py --write`", file=sys.stderr)
                raise SystemExit(1)
            print("imports.py --check: dag.bzl is fresh")
            raise SystemExit(0)
        if dag.read_text() == want:
            print("imports.py --write: dag.bzl already fresh")
            raise SystemExit(0)
        sys.path.insert(0, str(eng))
        import durable
        durable.write_atomic(dag, want)      # Ζ·write·atomic — the generator eats its own cooking
        print("imports.py --write: regenerated paperkit/dag.bzl")
        raise SystemExit(0)

    paths = argv
    names = {Path(p).stem for p in paths}
    for p in paths:
        stem = Path(p).stem
        for imp in sorted(imports(Path(p).read_text(), names) - {stem}):
            print("{}\t{}".format(p, imp))
